package com.medical.doc4all.service.impl;


import com.medical.doc4all.dto.*;
import com.medical.doc4all.entity.*;
import com.medical.doc4all.enums.InvitationStatus;
import com.medical.doc4all.enums.PaymentStatus;
import com.medical.doc4all.enums.Responses;
import com.medical.doc4all.exception.ResourceNotFoundException;
import com.medical.doc4all.repository.BookingRepository;
import com.medical.doc4all.repository.DispensaryRepository;
import com.medical.doc4all.repository.DoctorScheduleRepository;
import com.medical.doc4all.service.DispensaryService;
import com.medical.doc4all.repository.mapper.DispensaryMapper;
import jakarta.persistence.EntityNotFoundException;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Transactional
public class DispensaryServiceImpl implements DispensaryService {

    private final DispensaryRepository dispensaryRepository;
    private final DispensaryMapper dispensaryMapper;
    private final DoctorScheduleRepository scheduleRepository;
    private final BookingRepository bookingRepository;
    //private final DispensaryRepository dispensaryRepository;

    @Override
    public DispensaryResponse createDispensary(DispensaryCreateRequest request) {
        // Check if dispensary already exists
        if (dispensaryRepository.existsByEmail(request.getEmail())) {
            throw new RuntimeException("Dispensary with email " + request.getEmail() + " already exists");
        }

        Dispensary dispensary = Dispensary.builder()
                .id(null) // ID will be generated by the database
                .name(request.getName())
                .email(request.getEmail())
                .build();


        Dispensary savedDispensary = dispensaryRepository.save(dispensary);
        return dispensaryMapper.toResponse(savedDispensary);
    }

    @Override
    public MessageResponse updateDispensaryValidity(String email, boolean isValid) {
        Dispensary dispensary = dispensaryRepository.findByEmail(email)
                .orElseThrow(() -> new RuntimeException("Dispensary not found with email: " + email));

        //dispensary.setIsValid(isValid);
        dispensaryRepository.save(dispensary);

        String message = isValid ?
                "Dispensary has been approved and is now valid" :
                "Dispensary has been rejected and is now invalid";

        return MessageResponse.builder()
                .message(message)
                .success(true)
                .build();
    }

    @Override
    public Responses checkProfileStatus(String email) {
        Dispensary dispensary = dispensaryRepository.findByEmail(email)
                .orElseThrow(() -> new RuntimeException("Dispensary not found with email: " + email));

        // Check if all required fields are filled
        boolean isComplete = dispensary.getName() != null && !dispensary.getName().isEmpty()
                && dispensary.getEmail() != null && !dispensary.getEmail().isEmpty() && dispensary.getAddress() != null
                && !dispensary.getAddress().isEmpty() && dispensary.getLatitude() != null && dispensary.getLongitude() != null
                && dispensary.getContactNumber() != null && !dispensary.getContactNumber().isEmpty();

        // Add other required fields as necessary

        return isComplete ? Responses.Success : Responses.Failure;
    }

    public void updateDispensaryProfile(String userEmail, DispensaryProfileRequest request) {
        // Validate email
        if (userEmail == null || userEmail.trim().isEmpty()) {
            throw new IllegalArgumentException("User email is required");
        }

        // Find dispensary
        Dispensary dispensary = dispensaryRepository.findByEmail(userEmail)
                .orElseThrow(() -> new IllegalArgumentException("Dispensary not found with email: " + userEmail));

        // Update dispensary
        mapRequestToDispensary(dispensary, request);

        // Save
        dispensaryRepository.save(dispensary);

        //log.info("Successfully updated dispensary profile for user: {}", userEmail);
    }

    public DispensaryProfileResponse getProfileByEmail(String email) {
        Dispensary dispensary = dispensaryRepository.findByEmail(email)
                .orElseThrow(() -> new EntityNotFoundException("Dispensary not found"));

        DispensaryProfileResponse response = new DispensaryProfileResponse();
        response.setEmail(dispensary.getEmail());
        response.setPhone(dispensary.getContactNumber());
        response.setAddress(dispensary.getAddress());

        // Split name if needed
        String[] parts = dispensary.getName() != null ? dispensary.getName().split(" ", 2) : new String[]{"", ""};
        response.setFirstName(parts[0]);
        response.setLastName(parts.length > 1 ? parts[1] : "");

        response.setName(dispensary.getName());
        response.setLongitude(dispensary.getLongitude());
        response.setLatitude(dispensary.getLatitude());
        response.setDescription(dispensary.getDescription());
        response.setWebsite(dispensary.getWebsite());
        response.setType(dispensary.getType());
        response.setUpdatedAt(dispensary.getUpdatedAt());

        return response;
    }


    private void mapRequestToDispensary(Dispensary dispensary, DispensaryProfileRequest request) {
        // Update dispensary fields
        if (request.getAddress() != null) {
            dispensary.setAddress(request.getAddress());
        }
        if (request.getContactNumber() != null) {
            dispensary.setContactNumber(request.getContactNumber());
        }
        if (request.getType() != null) {
            dispensary.setType(DispensaryType.valueOf(request.getType()));
        }
        if (request.getDescription() != null) {
            dispensary.setDescription(request.getDescription());
        }
        if (request.getLatitude() != 0) {
            dispensary.setLatitude(request.getLatitude());
        }
        if (request.getLongitude() != 0) {
            dispensary.setLongitude(request.getLongitude());
        }
        if (request.getWebsite() != null) {
            dispensary.setWebsite(request.getWebsite());
        }
    }

    @Override
    @Transactional(readOnly = true)
    public DispensaryResponse getDispensaryByEmail(Long id) {
        Dispensary dispensary = dispensaryRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Dispensary not found with email: "));

        return dispensaryMapper.toResponse(dispensary);
    }

    @Override
    @Transactional(readOnly = true)
    public DispensaryDetailsDTO getDispensaryDetails(Long dispensaryId, LocalDate forDate) {
        Dispensary d = dispensaryRepository.findById(dispensaryId)
                .orElseThrow(() -> new ResourceNotFoundException("Dispensary not found: " + dispensaryId));

        List<DoctorSchedule> schedules = scheduleRepository.findByDispensaryIdAndStatus(dispensaryId, InvitationStatus.ACCEPTED);

        DispensaryDetailsDTO out = new DispensaryDetailsDTO();
        out.setId(d.getId());
        out.setName(d.getName());
        out.setAddress(d.getAddress());
        out.setLongitude(d.getLongitude());
        out.setLatitude(d.getLatitude());
        out.setRating(d.getRating());
        out.setDescription(d.getDescription());
        out.setContactNumber(d.getContactNumber());
        out.setWebsite(d.getWebsite());
        out.setType(d.getType());

        List<DoctorScheduleResponseDTO> scheduleDtos = schedules.stream()
                .map(s -> {
                    DoctorScheduleResponseDTO dto = new DoctorScheduleResponseDTO();
                    dto.setScheduleId(s.getId());
                    dto.setDoctorId(s.getDoctor().getId());
                    dto.setDoctorName(s.getDoctor().getName());
                    dto.setDoctorEmail(s.getDoctor().getEmail());
                    dto.setSpecialities(s.getDoctor().getSpecialities());
                    dto.setEducation(s.getDoctor().getEducation());
                    dto.setDay(s.getDay());
                    dto.setStartTime(s.getStartTime());
                    dto.setEndTime(s.getEndTime());
                    dto.setPerPatientMinutes(s.getPerPatientMinutes());
                    dto.setRate(s.getAgreedRate());
                    return dto;
                })
                .collect(Collectors.toList());

        out.setApprovedDoctors(scheduleDtos);
        return out;
    }

    @Override
    @Transactional(readOnly = true)
    public List<DispensaryResponse> getAllDispensaries() {
        List<Dispensary> dispensaries = dispensaryRepository.findAll();
        return dispensaries.stream()
                .map(dispensaryMapper::toResponse)
                .collect(Collectors.toList());
    }

    @Override
    public BookingResponseDTO completeBooking(Long bookingId){
        Booking b = bookingRepository.findById(bookingId)
                .orElseThrow(() -> new ResourceNotFoundException("Booking not found with id: " + bookingId));
        if(b.getPaymentStatus().equals(PaymentStatus.PAID)){
            b.setStatus(com.medical.doc4all.enums.BookingStatus.COMPLETED);
            bookingRepository.save(b);
            return toResponse(b);
        } else {
            throw new IllegalStateException("Cannot complete booking with payment status: " + b.getPaymentStatus());
        }
    }

    public void updateLocation(String userEmail, updateLocationDTO request){
        Dispensary dispensary = dispensaryRepository.findByEmail(userEmail)
                .orElseThrow(() -> new IllegalArgumentException("Dispensary not found with email: " + userEmail));

        dispensary.setLatitude(request.getLatitude());
        dispensary.setLongitude(request.getLongitude());

        dispensaryRepository.save(dispensary);
    }

    @Override
    public List<BookingResponseDTO> getBookingsForDispensary(String email) {
        Dispensary dispensary = dispensaryRepository.findByEmail(email)
                .orElseThrow(() -> new ResourceNotFoundException("Dispensary not found with email: " + email));

        List<DoctorSchedule> schedules = scheduleRepository.findByDispensaryId(dispensary.getId());

        List<Booking> bookings = schedules.stream()
                .flatMap(schedule -> bookingRepository.findBySchedule(schedule).stream())
                .collect(Collectors.toList());

        return bookings.stream()
                .map(this::toResponse)
                .collect(Collectors.toList());
    }

    private BookingResponseDTO toResponse(Booking booking) {
        DoctorSchedule schedule = booking.getSchedule();
        Doctor doctor = (schedule != null ? schedule.getDoctor() : null);
        Patient patient = booking.getPatient();

        DoctorDTO doctorDTO = null;
        if (doctor != null) {
            doctorDTO = DoctorDTO.builder()
                    .id(doctor.getId())
                    .name(doctor.getName())
                    .email(doctor.getEmail())
                    .type(doctor.getType() != null ? doctor.getType().name() : null)
                    .experience(doctor.getExperience())
                    .specialities(doctor.getSpecialities())
                    .education(doctor.getEducation())
                    .build();
        }

        return BookingResponseDTO.builder()
                .bookingId(booking.getId())
                .patientName(patient != null ? patient.getName() : null)
                .doctorName(doctor != null ? doctor.getName() : null)
                .dispensaryName(schedule != null && schedule.getDispensary() != null ? schedule.getDispensary().getName() : null)
                .appointmentDate(booking.getAppointmentDate())
                .appointmentTime(booking.getSlotStartTime())
                .status(booking.getStatus() != null ? booking.getStatus().name() : null)
                .paymentStatus(booking.getPaymentStatus() != null ? booking.getPaymentStatus().name() : null)
                .transactionId(booking.getTransactionId())
                .refundTransactionId(booking.getRefundTransactionId())
                .doctor(doctorDTO)
                .build();
    }



}
