spring.application.name=doc4all

spring.datasource.url = jdbc:postgresql://localhost:5432/dispensary
spring.datasource.username = piranaavei
spring.datasource.password=PiRa$18N
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = update

logging.level.org.springframework.web=DEBUG
logging.level.com.fasterxml.jackson=DEBUG

braintree.environment=SANDBOX
braintree.merchantId=ddrj8vq5wp8zb4zm
braintree.publicKey=pth5gmwb5kwjvymg
braintree.privateKey=4d15d4b959c04451b6ba79ff80d43ac7

reports.masterKeyBase64=+bY9LIN4JOcV4ZpWB7QHYQ==

# Mailtrap SMTP settings
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=2560454d70fce0
spring.mail.password=47857b0449fa89
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

# Actuator configuration
management.endpoints.web.exposure.include=health,prometheus,info
