spring.application.name=bff
server.port=8005
app.upload.dir=uploads/certificates

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url = jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username = piranaavei
spring.datasource.password=PiRa$18N
spring.datasource.driver-class-name=org.postgresql.Driver

## Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jwt.secret=a1ce6d670aec166476c58af6f8d7a304e14e1e00da08a316e03ca94596ddf05a30cab3b1cf0b4ac69fe77276134a19f5ff34614b21d72d08b6d7b9c27a7ea74c
jwt.expiration=86400000

# Set root logging level to INFO (default)
logging.level.root=INFO

# Enable DEBUG logs for your application's packages
logging.level.com.med4all.bff=DEBUG

# Log SQL queries (if using JPA/Hibernate)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BASIC=TRACE

# Log Spring Web details (controllers, requests)
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# Optional: Log to a file
logging.file.name=logs/application.log